/*
   den 21 mars 2003 17:04:31
   User: sa
   Server: LENNART
   Database: allerannons
   Application: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.poll_questions
	DROP CONSTRAINT IX_poll_questions_1
GO
ALTER TABLE dbo.poll_questions ADD CONSTRAINT
	IX_poll_questions_1 UNIQUE NONCLUSTERED 
	(
	poll_id,
	question_number,
	text_id
	) ON [PRIMARY]

GO
COMMIT
